name: .NET Core / app.immutable

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache init
      id: cache-id1
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: .github/workflows/cache
        # An explicit key for restoring and saving the cache
        key: cache-app.immutable.command
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: app.immutable.command
    
    - name: Generate Prime Numbers
      if: steps.cache-id1.outputs.cache-hit != 'true'
      run: steps.setup-dotnet-id1
    
    - name: dotnet restore, build-release, test on app.immutable.command
      id: setup-dotnet-id1
      uses: actions/setup-dotnet@v1
      with:
        key: app.immutable.command
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
